
PREFIX p:         <http://www.wikidata.org/prop/>
PREFIX psv:       <http://www.wikidata.org/prop/statement/value/>
PREFIX wikibase:  <http://wikiba.se/ontology#>
PREFIX wd:       <http://www.wikidata.org/entity/>
PREFIX wdt:      <http://www.wikidata.org/prop/direct/>

SELECT ?city ?areaInSqMi ?areaInSqMeters
WHERE {

	?city wdt:P31 wd:Q515. #city subclasses of city also annotated as cities
	
	?city  p:P2046 ?valueNodeStm. # area property
	?valueNodeStm psv:P2046 ?quantityValue.
	?quantityValue wikibase:quantityAmount ?areaInSqMi.
	?quantityValue wikibase:quantityUnit  wd:Q232291. # retrieve the area in square miles


	?city  p:P2046 ?valueNodeStm2. # area property
    ?valueNodeStm2 psv:P2046 ?quantityValue2.
    ?quantityValue2 wikibase:quantityAmount ?areaInSqMeters.
    ?quantityValue2 wikibase:quantityUnit  wd:Q25343. # retrieve the area in square meters

    # most of the data is in square kilometers
}
